name: flutter_moshimoshi
description: "A powerful package for optimizing communication between Flutter applications and HTTP servers. Crafted to simplify the complexities of HTTP requests, authentication, and data storage, MooshiMoshi offers a robust toolkit of utilities and abstractions."
version: 1.0.10

homepage: https://github.com/fsalom/flutter-moshimoshi
repository: https://github.com/fsalom/flutter-moshimoshi
issue_tracker: https://github.com/fsalom/flutter-moshimoshi/issues
license: MIT

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.32.8 <4.0.0"

dependencies:
  dio: ">=5.8.0 <6.0.0"
  flutter:
    sdk: flutter
  flutter_bloc: ">=9.1.0 <10.0.0"
  http: ">=1.5.0 <2.0.0"
  hybrid_logger: ">=1.0.5 <2.0.0"
  shared_preferences: ">=2.5.3 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.6.0

flutter:
  uses-material-design: true
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
